name: Self-Hosted Linux Workflow

on:
  push:
    branches: 
    - main
    
  pull_request:
    branches: 
    - main

jobs:
  build: linux-self-hosted-ARM64-runner
    name: Build on Self-Hosted Linux
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
       uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262

      - name: Set up Node.js 24
       uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
  with:
    node-version: '24'
      
      - name: Install Dependencies
        run: |
          npm install

      - name: Run Tests
        run: npm test

      - name: Build Project
        run: |
          npm run build
